### PR TITLE
Support of Ultra96V2 board

### PR DESCRIPTION
**Pull request by malus-brandywine**

### CODE REVIEW

**Comment by Ivan-Velickovic** [comment]
Thanks! I will need to look deeper into SMC/SiP first before reviewing. I'll also try your Linux images with the ZCU102 as I briefly attempted to get it working (https://github.com/Ivan-Velickovic/sel4cp_vmm/pull/8) but got stuck and haven't had the chance to return to it.

**Comment by Ivan-Velickovic** [comment]
Another thing is that in order for the example to build/run correctly we'll need to have the changes in the seL4 branch used by seL4CP as well as seL4CP itself first.

**Comment by Ivan-Velickovic** [comment]
> Yes, I used the Manual's porting section to figure out what changes have to be done in sel4cp_vmm (very useful, thank you!). Linux image section gives general overview, in my opinion that's enough, board-specific instructions probably should go to a board directory like it was mentioned in the manual.

Great to hear! I have some more https://github.com/Ivan-Velickovic/sel4cp_vmm/pull/11 details coming soon for those not too familiar with building the Linux kernel (as I was when I started working with this stuff).

> 
> I wrote READMEs in both [petalinux-ultra96v2-sel4cpvmm](https://github.com/malus-brandywine/petalinux-ultra96v2-sel4cpvmm) and [ultra96v2_sel4cpvmm](https://github.com/malus-brandywine/ultra96v2_sel4cpvmm) projects; there are explanations how to reproduce the image and how sel4cp_vmm was modified. I can compose readme-light with reference to the both projects and put it in the sel4cp_vmm's the board directory.

Cool, thanks for doing those. I can't remember if it's documented in the manual, but *every* artifact that is in the repository should have the associated configuration file for reproducing from scratch (e.g Linux config or Buildroot config) as well as instructions for how to reproduce the artifacts/images. I admit that this isn't adhered to completely right now in the repo, but am actively working on fixing up all the board images and READMEs.

> Briefly about the artefacts I provided: I used default Linux configuration which is provided in Avnet scripts; I picked up dtb built by the Avnet scripts, de-compiled it to dts and commented not passed-through devices.

If you could also document this in the board specific README that would be great.

**Comment by Ivan-Velickovic** [comment]
Waiting for https://github.com/Ivan-Velickovic/sel4cp_vmm/pull/10 to be done and merged before dealing with any other PRs by the way. Just so you know that I haven't forgotten about yours.

**Comment by malus-brandywine** [comment]
Thank you for letting me know! I owe a README, I remember, it's coming soon.

**Comment by malus-brandywine** [comment]
> If you could also document this in the board specific README that would be great.

Did my best at the moment !

**Comment by Ivan-Velickovic** [comment]
My first main question is, does Xilinx enforce the use of PetaLinux? Is building the mainline Linux not supported at all?

The reason I ask is, while not completely opposed to it, wary of using non-mainline versions of Linux.

**Comment by malus-brandywine** [comment]
Very well,  just to be on the same page...

First, PetaLinux is an SDK that allows to build all the artefacts for linux distribution in the manner that they are matched. For example, if you add Xen in the distribution, then linux kernel and init scripts will be properly configured/patched, the hypervisor itself along with proper user space utilities will be added. That's all about making a consistent distribution.

Second, PetaLinux fetches and builds Xilinx kernel tree - "linux-xlnx". They keep it pretty much new making merges from the mainline, however some fresh drivers might be missing from mainline. So, my answer is - one can use any of the trees depending on the specific case.

**Comment by malus-brandywine** [comment]
I'm integrating SiP functions forwarding to the new source tree structure...

**Comment by Ivan-Velickovic** [comment]
> I'm integrating SiP functions forwarding to the new source tree structure...

Cool, the main thing I was going to say for the Ultra96V2 support is to have a README for the images that follows a similar style to https://github.com/au-ts/libvmm/blob/main/examples/simple/board/qemu_arm_virt/README.md, just for consistency.

**Pull request closed without merging**
