### PR TITLE
Add DMA passthrough section to manual

### PR DESCRIPTION
**Pull request by alexandermbrown**
Add DMA passthrough section to manual

### CODE REVIEW

**Review by wom-bat — APPROVED** [review]
LGTM.

**Comment by Ivan-Velickovic** [comment]
These PRs are left unmerged because there are changes to be made

**Comment by alexandermbrown** [comment]
@Ivan-Velickovic would you be able to comment what needs to be done next time? I was also unsure why this was sitting here.

**Comment by Ivan-Velickovic** [comment]
> @Ivan-Velickovic would you be able to comment what needs to be done next time? I was also unsure why this was sitting here.

Yes, my bad for not responding to the PR.

From memory there was one change I wanted to make but I can't remember now and the content looks good. I want to make some additions so I can just do that in a separate PR.

Thanks for improving the docs.

**Pull request merged**
